# Site settings
# Enter your own credentials here
title: "My Blog"
email: you@somewhere.com
description: >
  To illustrate data sharing on Research Mini Sites.
baseurl: "/data-pages-demo" # replace ``/research-pages`` with the name of the parents repository
url: "Materials-Informatics-Lab.github.io" # replate ``Materials-Informatics-Lab`` with your Github username
twitter_username: twitterhandle
disqus: tonyfast

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5


gh:
  user: Materials-Informatics-Lab
  repo: data-pages-demo
  # Branch hosting Github pages
  branch: gh-pages
